# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetGnu <- function(z, breaks, lIN, lOut) {
    .Call(`_CpDyna_GetGnu`, z, breaks, lIN, lOut)
}

GnuToX <- function(EGnu, Eptn, N) {
    .Call(`_CpDyna_GnuToX`, EGnu, Eptn, N)
}

VM_MP <- function(Etau, ptn, EGnu, PeltOrNot = TRUE) {
    .Call(`_CpDyna_VM_MP`, Etau, ptn, EGnu, PeltOrNot)
}

VM_MP_ <- function(Etau, ptn, EGnu, PeltOrNot = TRUE) {
    .Call(`_CpDyna_VM_MP_`, Etau, ptn, EGnu, PeltOrNot)
}

LowerBound_MP <- function(Etau, EGnu, ptn, Pi, Lbd) {
    .Call(`_CpDyna_LowerBound_MP`, Etau, EGnu, ptn, Pi, Lbd)
}

VE_MP <- function(Etau, ptn, Pi, Lbd, EX, EGnu) {
    .Call(`_CpDyna_VE_MP`, Etau, ptn, Pi, Lbd, EX, EGnu)
}

GetX <- function(U, ptn, z, breaks, lIN, lOut) {
    .Call(`_CpDyna_GetX`, U, ptn, z, breaks, lIN, lOut)
}

VE_ <- function(Etau, ptn, ValuesAtPtn, Pi, Lbd, EX) {
    .Call(`_CpDyna_VE_`, Etau, ptn, ValuesAtPtn, Pi, Lbd, EX)
}

VM <- function(Etau, ptn, EX, PeltOrNot = TRUE) {
    .Call(`_CpDyna_VM`, Etau, ptn, EX, PeltOrNot)
}

VM_ <- function(Etau, ptn, EX, PeltOrNot = TRUE, MinimalPartition = TRUE) {
    .Call(`_CpDyna_VM_`, Etau, ptn, EX, PeltOrNot, MinimalPartition)
}

LowerBound <- function(Etau, EX, ptn, Pi, Lbd) {
    .Call(`_CpDyna_LowerBound`, Etau, EX, ptn, Pi, Lbd)
}

LowerBound_ <- function(Etau, EX, ptn, Pi, Lbd, LLbd, ValuesAtPtn) {
    .Call(`_CpDyna_LowerBound_`, Etau, EX, ptn, Pi, Lbd, LLbd, ValuesAtPtn)
}

GetDistance <- function(EX) {
    .Call(`_CpDyna_GetDistance`, EX)
}

GetDistance2 <- function(EX) {
    .Call(`_CpDyna_GetDistance2`, EX)
}

